
"""
AGENTCOMMERCE OS
PHASE 08.1 — POLICY MODELS

Deterministic models used by the Policy Engine.

Important:
    These models contain no LLM logic.
    The Policy Engine is the authority for financial decisions.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional


# ============================================================
# POLICY DECISION
# ============================================================

class PolicyDecision(str, Enum):
    ALLOW = "ALLOW"
    MODIFY = "MODIFY"
    DENY = "DENY"
    ESCALATE = "ESCALATE"


# ============================================================
# POLICY REASON CODES
# ============================================================

class PolicyReasonCode(str, Enum):
    DISCOUNT_LIMIT_EXCEEDED = "DISCOUNT_LIMIT_EXCEEDED"
    MINIMUM_MARGIN_VIOLATED = "MINIMUM_MARGIN_VIOLATED"
    MAX_ORDER_VALUE_EXCEEDED = "MAX_ORDER_VALUE_EXCEEDED"
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    PRODUCT_OUT_OF_STOCK = "PRODUCT_OUT_OF_STOCK"
    INVALID_PRICE = "INVALID_PRICE"
    INVALID_DISCOUNT = "INVALID_DISCOUNT"
    NEGOTIATION_LIMIT_EXCEEDED = "NEGOTIATION_LIMIT_EXCEEDED"
    CUSTOMER_APPROVAL_REQUIRED = "CUSTOMER_APPROVAL_REQUIRED"
    MERCHANT_APPROVAL_REQUIRED = "MERCHANT_APPROVAL_REQUIRED"
    POLICY_CONFLICT = "POLICY_CONFLICT"
    INVALID_REQUEST = "INVALID_REQUEST"


# ============================================================
# MERCHANT POLICY
# ============================================================

@dataclass
class MerchantPolicy:
    """
    Merchant-controlled financial and agent-authority limits.
    """

    max_discount_percent: float = 10.0

    min_margin_percent: float = 10.0

    max_order_value: Optional[float] = None

    max_negotiation_rounds: int = 2

    max_free_shipping_cost: float = 100.0

    upsell_allowed: bool = True

    cross_sell_allowed: bool = True

    requires_customer_confirmation: bool = True

    auto_approve_discount_percent: float = 5.0

    auto_approve_order_value: float = 5000.0


# ============================================================
# PRODUCT ECONOMICS
# ============================================================

@dataclass
class ProductEconomics:
    """
    Trusted product information supplied by the catalog/database.
    """

    product_id: int

    list_price: float

    cost_price: float

    inventory_available: bool = True


# ============================================================
# OFFER PROPOSAL
# ============================================================

@dataclass
class OfferProposal:
    """
    Proposal generated by the Merchant Agent.

    The proposal is NOT automatically trusted.
    It must pass through the Policy Engine.
    """

    product_id: int

    requested_price: float

    negotiation_round: int = 0

    customer_requested_discount: Optional[float] = None


# ============================================================
# POLICY RESULT
# ============================================================

@dataclass
class PolicyResult:
    """
    Final deterministic decision.
    """

    decision: PolicyDecision

    original_price: float

    requested_price: float

    approved_price: Optional[float]

    discount_percent: float

    margin_amount: float

    reason_codes: List[PolicyReasonCode] = field(
        default_factory=list
    )

    requires_human_approval: bool = False

    message: str = ""

    evidence: dict = field(
        default_factory=dict
    )


def main():
    print("AGENTCOMMERCE OS - POLICY MODELS")
    print("Policy decisions:")
    print(", ".join(decision.value for decision in PolicyDecision))
    print("Policy reason codes:")
    print(", ".join(reason.value for reason in PolicyReasonCode))

    print("\nSample merchant policy:")
    print(MerchantPolicy())

    print("\nSample product economics:")
    print(ProductEconomics(
        product_id=453,
        list_price=784.23,
        cost_price=350.00,
    ))

    print("\nSample offer proposal:")
    print(OfferProposal(
        product_id=453,
        requested_price=705.81,
        customer_requested_discount=10.0,
    ))


if __name__ == "__main__":
    main()

